-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgs/Vk6nRNIJ6EZfqn
+Xnsm5jItFdvCuDzSk9SPANugkagCgYIKoZIzj0DAQehRANCAASEnxEAwPTafISh
MZIyqNAVXRsf0zyUJYUmfNy6DtfAvTrQDrjkLcqSeoeNCo27MCtHUWn5zDwQQFyU
VrpaKiOW
-----END PRIVATE KEY-----